In [1]:
import numpy as np
import pandas as pd

<h6>SaleData is import </h6>

In [2]:
df=pd.read_excel('salereport.xlsx')
df

          Chain  Potcode     Category  T.U     C.P     S.P
0    Ready Wear     2650         Home  175    2.78    6.35
1    Ready Wear     3550    Groceries  908    0.61    0.93
2    Ready Wear     4053         Home    1  500.00  750.00
3    Ready Wear     3076    Groceries  714    1.14    1.46
4    Ready Wear     2031    Groceries   65    0.48    3.90
5    Ready Wear     3066         Home   87    3.66    6.19
6    Ready Wear     2067         Home   92    5.21    7.34
7    Ready Wear     2800         Home   21    4.49   13.55
8    Ready Wear     2560         Home  127    4.19    5.59
9    Ready Wear     3076         Home   77    4.73    6.99
10   Ready Wear      800       Womens    2   10.00   18.53
11   Ready Wear     2031    Groceries  898    1.20    1.39
12   Ready Wear     4068         Home  170    4.15    5.13
13   Ready Wear      800       Womens   50    1.90    1.92
14   Ready Wear     4068       Womens  166    2.51    3.43
15   Ready Wear     2350         Home  213    2.37    3.07
16   Ready Wear     3353         Home  116    4.62    5.80
17   Ready Wear     3550    Groceries  233    0.94    1.52
18   Ready Wear     3018    Groceries  283    1.17    1.64
19   Ready Wear      800       Womens    3    7.00    6.75
20   Ready Wear     2020         Home   81    6.67    8.17
21   Ready Wear      800       Womens    2   10.00    7.51
22   Ready Wear     3550         Kids   65    2.19    3.92
23   Ready Wear     3066         Home  934    1.87    1.99
24   Ready Wear     3148         Home   69    2.12    3.67
25   Ready Wear     3550  Accessories   40   11.32   13.78
26   Ready Wear     6330         Home  143    4.81    5.45
27   Ready Wear     2480      Juniors   18    5.56   10.51
28   Ready Wear      800       Womens   15    3.93    3.43
29   Ready Wear     3353       Womens   19    8.10   12.63
..          ...      ...          ...  ...     ...     ...
869  Ready Wear     3066  Accessories    1    5.99    1.00
870  Ready Wear     3076  Accessories    1    5.99    1.00
871    Bellings     3630       Womens    1   14.99   10.00
872  Ready Wear     4068      Juniors    1   14.99   10.00
873  Ready Wear     4509  Accessories    1    5.99    1.00
874    Bellings     4655         Mens    1    9.99    5.00
875    Bellings     4825      Juniors    1   14.99   10.00
876    Bellings     4870         Mens    1    9.99    5.00
877    Bellings     6027         Mens    1    7.99    3.00
878    Bellings      870         Home    4    3.50    2.25
879    Bellings     2064         Mens    2    7.00    4.50
880  Ready Wear     2800  Accessories   23    2.22    2.00
881    Bellings     5011         Kids    5    4.00    3.00
882    Bellings     5011      Juniors    1   14.00    9.00
883    Bellings     6112         Home    4    3.50    2.25
884  Ready Wear     3066      Juniors   32   11.64   11.48
885    Bellings      870  Accessories   10    1.49    0.97
886    Bellings     4655         Kids    4    1.80    0.50
887  Ready Wear     2795         Kids    3    4.99    3.25
888  Ready Wear     3148      Juniors    9    9.11    8.53
889    Bellings     3500         Mens    2    5.49    2.88
890    Bellings     7010  Accessories    4   10.25    8.94
891    Bellings     2064         Mens    3    7.00    5.25
892    Bellings     2120      Juniors    1    7.99    2.74
893    Bellings     3429      Juniors    1    7.99    2.74
894  Ready Wear     3551     Intimate   70    0.55    0.48
895    Bellings     4305         Home    3    5.00    3.24
896    Bellings     3500  Accessories   17    4.23    3.92
897  Ready Wear     4551       Womens  150    2.71    2.67
898  Ready Wear     3353      Hosiery    4    1.99    0.65

[899 rows x 6 columns]

<h6>Renaming the columns</h6>

In [3]:
df.rename(columns={"Potcode": "Postcode", "T.U": "Total Unit" ,"S.P": "Sales Price", "C.P": "Cost Price"},inplace=True)

In [4]:
df

          Chain  Postcode     Category  Total Unit  Cost Price  Sales Price
0    Ready Wear      2650         Home         175        2.78         6.35
1    Ready Wear      3550    Groceries         908        0.61         0.93
2    Ready Wear      4053         Home           1      500.00       750.00
3    Ready Wear      3076    Groceries         714        1.14         1.46
4    Ready Wear      2031    Groceries          65        0.48         3.90
5    Ready Wear      3066         Home          87        3.66         6.19
6    Ready Wear      2067         Home          92        5.21         7.34
7    Ready Wear      2800         Home          21        4.49        13.55
8    Ready Wear      2560         Home         127        4.19         5.59
9    Ready Wear      3076         Home          77        4.73         6.99
10   Ready Wear       800       Womens           2       10.00        18.53
11   Ready Wear      2031    Groceries         898        1.20         1.39
12   Ready Wear      4068         Home         170        4.15         5.13
13   Ready Wear       800       Womens          50        1.90         1.92
14   Ready Wear      4068       Womens         166        2.51         3.43
15   Ready Wear      2350         Home         213        2.37         3.07
16   Ready Wear      3353         Home         116        4.62         5.80
17   Ready Wear      3550    Groceries         233        0.94         1.52
18   Ready Wear      3018    Groceries         283        1.17         1.64
19   Ready Wear       800       Womens           3        7.00         6.75
20   Ready Wear      2020         Home          81        6.67         8.17
21   Ready Wear       800       Womens           2       10.00         7.51
22   Ready Wear      3550         Kids          65        2.19         3.92
23   Ready Wear      3066         Home         934        1.87         1.99
24   Ready Wear      3148         Home          69        2.12         3.67
25   Ready Wear      3550  Accessories          40       11.32        13.78
26   Ready Wear      6330         Home         143        4.81         5.45
27   Ready Wear      2480      Juniors          18        5.56        10.51
28   Ready Wear       800       Womens          15        3.93         3.43
29   Ready Wear      3353       Womens          19        8.10        12.63
..          ...       ...          ...         ...         ...          ...
869  Ready Wear      3066  Accessories           1        5.99         1.00
870  Ready Wear      3076  Accessories           1        5.99         1.00
871    Bellings      3630       Womens           1       14.99        10.00
872  Ready Wear      4068      Juniors           1       14.99        10.00
873  Ready Wear      4509  Accessories           1        5.99         1.00
874    Bellings      4655         Mens           1        9.99         5.00
875    Bellings      4825      Juniors           1       14.99        10.00
876    Bellings      4870         Mens           1        9.99         5.00
877    Bellings      6027         Mens           1        7.99         3.00
878    Bellings       870         Home           4        3.50         2.25
879    Bellings      2064         Mens           2        7.00         4.50
880  Ready Wear      2800  Accessories          23        2.22         2.00
881    Bellings      5011         Kids           5        4.00         3.00
882    Bellings      5011      Juniors           1       14.00         9.00
883    Bellings      6112         Home           4        3.50         2.25
884  Ready Wear      3066      Juniors          32       11.64        11.48
885    Bellings       870  Accessories          10        1.49         0.97
886    Bellings      4655         Kids           4        1.80         0.50
887  Ready Wear      2795         Kids           3        4.99         3.25
888  Ready Wear      3148      Juniors           9        9.11         8.53
889    Bellings      3500         Mens           2        5.49         2.88
890    Bellings      7010  Accessories           4       10.25         8.94
891    Bellings      2064         Mens           3        7.00         5.25
892    Bellings      2120      Juniors           1        7.99         2.74
893    Bellings      3429      Juniors           1        7.99         2.74
894  Ready Wear      3551     Intimate          70        0.55         0.48
895    Bellings      4305         Home           3        5.00         3.24
896    Bellings      3500  Accessories          17        4.23         3.92
897  Ready Wear      4551       Womens         150        2.71         2.67
898  Ready Wear      3353      Hosiery           4        1.99         0.65

[899 rows x 6 columns]

In [5]:
df.dtypes

Chain           object
Postcode         int64
Category        object
Total Unit       int64
Cost Price     float64
Sales Price    float64
dtype: object

In [6]:
type(df)

pandas.core.frame.DataFrame

<h6>Searching for Null Values</h6>

In [7]:
df.isnull()

     Chain  Postcode  Category  Total Unit  Cost Price  Sales Price
0    False     False     False       False       False        False
1    False     False     False       False       False        False
2    False     False     False       False       False        False
3    False     False     False       False       False        False
4    False     False     False       False       False        False
5    False     False     False       False       False        False
6    False     False     False       False       False        False
7    False     False     False       False       False        False
8    False     False     False       False       False        False
9    False     False     False       False       False        False
10   False     False     False       False       False        False
11   False     False     False       False       False        False
12   False     False     False       False       False        False
13   False     False     False       False       False        False
14   False     False     False       False       False        False
15   False     False     False       False       False        False
16   False     False     False       False       False        False
17   False     False     False       False       False        False
18   False     False     False       False       False        False
19   False     False     False       False       False        False
20   False     False     False       False       False        False
21   False     False     False       False       False        False
22   False     False     False       False       False        False
23   False     False     False       False       False        False
24   False     False     False       False       False        False
25   False     False     False       False       False        False
26   False     False     False       False       False        False
27   False     False     False       False       False        False
28   False     False     False       False       False        False
29   False     False     False       False       False        False
..     ...       ...       ...         ...         ...          ...
869  False     False     False       False       False        False
870  False     False     False       False       False        False
871  False     False     False       False       False        False
872  False     False     False       False       False        False
873  False     False     False       False       False        False
874  False     False     False       False       False        False
875  False     False     False       False       False        False
876  False     False     False       False       False        False
877  False     False     False       False       False        False
878  False     False     False       False       False        False
879  False     False     False       False       False        False
880  False     False     False       False       False        False
881  False     False     False       False       False        False
882  False     False     False       False       False        False
883  False     False     False       False       False        False
884  False     False     False       False       False        False
885  False     False     False       False       False        False
886  False     False     False       False       False        False
887  False     False     False       False       False        False
888  False     False     False       False       False        False
889  False     False     False       False       False        False
890  False     False     False       False       False        False
891  False     False     False       False       False        False
892  False     False     False       False       False        False
893  False     False     False       False       False        False
894  False     False     False       False       False        False
895  False     False     False       False       False        False
896  False     False     False       False       False        False
897  False     False     False       False       False        False
898  False     False     False       False       False        False

[899 rows x 6 columns]

In [8]:
df.shape

(899, 6)

In [9]:
df.head()

        Chain  Postcode   Category  Total Unit  Cost Price  Sales Price
0  Ready Wear      2650       Home         175        2.78         6.35
1  Ready Wear      3550  Groceries         908        0.61         0.93
2  Ready Wear      4053       Home           1      500.00       750.00
3  Ready Wear      3076  Groceries         714        1.14         1.46
4  Ready Wear      2031  Groceries          65        0.48         3.90

In [10]:
df.T

,0,1,2,3,4,5,6,7,8,9,...,889,890,891,892,893,894,895,896,897,898
Chain,Ready Wear,Ready Wear,Ready Wear,Ready Wear,Ready Wear,Ready Wear,Ready Wear,Ready Wear,Ready Wear,Ready Wear,...,Bellings,Bellings,Bellings,Bellings,Bellings,Ready Wear,Bellings,Bellings,Ready Wear,Ready Wear
Postcode,2650,3550,4053,3076,2031,3066,2067,2800,2560,3076,...,3500,7010,2064,2120,3429,3551,4305,3500,4551,3353
Category,Home,Groceries,Home,Groceries,Groceries,Home,Home,Home,Home,Home,...,Mens,Accessories,Mens,Juniors,Juniors,Intimate,Home,Accessories,Womens,Hosiery
Total Unit,175,908,1,714,65,87,92,21,127,77,...,2,4,3,1,1,70,3,17,150,4
Cost Price,2.78,0.61,500,1.14,0.48,3.66,5.21,4.49,4.19,4.73,...,5.49,10.25,7,7.99,7.99,0.55,5,4.23,2.71,1.99
Sales Price,6.35,0.93,750,1.46,3.9,6.19,7.34,13.55,5.59,6.99,...,2.88,8.94,5.25,2.74,2.74,0.48,3.24,3.92,2.67,0.65

<h6>Arithmetic Operations</h6>

In [11]:
df['Total Cost']=df['Total Unit']*df['Cost Price']
df['Total Sales']=df['Total Unit']*df['Sales Price']
df['Profit']=df['Total Sales']-df['Total Cost']

In [12]:
df.head(10)

,Chain,Postcode,Category,Total Unit,Cost Price,Sales Price,Total Cost,Total Sales,Profit
0,Ready Wear,2650,Home,175,2.78,6.35,486.50,1111.25,624.75
1,Ready Wear,3550,Groceries,908,0.61,0.93,553.88,844.44,290.56
2,Ready Wear,4053,Home,1,500.00,750.00,500.00,750.00,250.00
3,Ready Wear,3076,Groceries,714,1.14,1.46,813.96,1042.44,228.48
4,Ready Wear,2031,Groceries,65,0.48,3.90,31.20,253.50,222.30
5,Ready Wear,3066,Home,87,3.66,6.19,318.42,538.53,220.11
6,Ready Wear,2067,Home,92,5.21,7.34,479.32,675.28,195.96
7,Ready Wear,2800,Home,21,4.49,13.55,94.29,284.55,190.26
8,Ready Wear,2560,Home,127,4.19,5.59,532.13,709.93,177.80
9,Ready Wear,3076,Home,77,4.73,6.99,364.21,538.23,174.02

In [13]:
df.describe()

,Postcode,Total Unit,Cost Price,Sales Price,Total Cost,Total Sales,Profit
count,899.000000,899.000000,899.000000,899.000000,899.000000,899.000000,899.000000
mean,3658.364850,29.726363,5.353204,5.774093,105.676474,100.945751,-4.730723
std,1562.458905,113.527165,17.001521,25.171068,361.789792,279.311595,119.046111
min,800.000000,-3.000000,-22.970000,0.250000,-42.970000,-20.000000,-1771.250000
25%,2560.000000,1.000000,2.000000,1.910000,5.990000,4.500000,-2.750000
50%,3429.000000,5.000000,4.000000,3.800000,17.000000,19.210000,0.000000
75%,4680.000000,15.500000,7.000000,7.000000,68.080000,76.745000,8.000000
max,7320.000000,1674.000000,500.000000,750.000000,5213.560000,4039.200000,624.750000