In [1]:
import numpy as np
import pandas as pd

In [2]:
dict = {
    "name":['fahad','faiz','faisal'],
    "marks":[45,35,25],
    "city":['pune','pune','pune']
}

In [3]:
df = pd.DataFrame(dict)

In [4]:
df

     name  marks  city
0   fahad     45  pune
1    faiz     35  pune
2  faisal     25  pune

<h6>coverting to CSV file with index 0,1,</h6>

In [5]:
df.to_csv('borther.csv')

<h6>coverting to CSV file without index 0,1,</h6>

In [6]:
df.to_csv('borther_indexfalse.csv',index=False)

In [7]:
df.head(2)

    name  marks  city
0  fahad     45  pune
1   faiz     35  pune

In [8]:
df.tail(1)

     name  marks  city
2  faisal     25  pune

<h6>Statical analysis for numerical column </h6>

In [9]:
df.describe()

       marks
count    3.0
mean    35.0
std     10.0
min     25.0
25%     30.0
50%     35.0
75%     40.0
max     45.0

<h6>Reading the CSV files</h6>

In [10]:
train =pd.read_csv('train.csv')

In [11]:
train

   Train  Speed        city
0  12534     45        pune
1  58751     35        pune
2  54552     25        pune
3  57361     30  aurangabad

In [12]:
train

   Train  Speed        city
0  12534     45        pune
1  58751     35        pune
2  54552     25        pune
3  57361     30  aurangabad

In [13]:
train ['Speed'][0]=75

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [14]:
train

   Train  Speed        city
0  12534     75        pune
1  58751     35        pune
2  54552     25        pune
3  57361     30  aurangabad

In [15]:
train.index=['first','second','third','fourth']

In [16]:
train

        Train  Speed        city
first   12534     75        pune
second  58751     35        pune
third   54552     25        pune
fourth  57361     30  aurangabad

<h3>Pandas data sturcture </h3>
<h6>Series:Series is a one-dimensional labeled array capable of holding any data type (integers, strings, floating point numbers, Python objects, etc.). The axis labels are collectively referred to as the index</h6>
<h6>DataFrame :DataFrame is a 2-dimensional labeled data structure with columns of potentially different types of data .</h6>

In [17]:
ser=pd.Series(np.random.rand(20))

In [18]:
ser

0     0.063835
1     0.139941
2     0.580931
3     0.775822
4     0.572012
5     0.721165
6     0.841487
7     0.554327
8     0.688856
9     0.619648
10    0.342764
11    0.337643
12    0.059871
13    0.675098
14    0.279591
15    0.844223
16    0.413733
17    0.480926
18    0.319399
19    0.332628
dtype: float64

In [19]:
type(ser)

pandas.core.series.Series

In [20]:
df=pd.DataFrame(np.random.rand(330,5))

In [21]:
df

            0         1         2         3         4
0    0.249591  0.400358  0.195161  0.485928  0.784790
1    0.768235  0.774584  0.986698  0.336482  0.408301
2    0.724468  0.604839  0.874132  0.691223  0.439762
3    0.858835  0.380090  0.644773  0.505105  0.329564
4    0.908892  0.772895  0.942653  0.337241  0.461231
5    0.186932  0.972758  0.446872  0.644623  0.370857
6    0.420970  0.809826  0.549558  0.116722  0.277077
7    0.127323  0.374748  0.138717  0.883066  0.298136
8    0.737604  0.171895  0.932980  0.090465  0.196444
9    0.943722  0.781767  0.756920  0.245574  0.553133
10   0.224846  0.004142  0.024532  0.971419  0.795797
11   0.408782  0.483285  0.218606  0.986162  0.626893
12   0.792973  0.863136  0.237447  0.858588  0.685894
13   0.900518  0.240991  0.984663  0.101751  0.332327
14   0.094454  0.481045  0.469216  0.655201  0.336626
15   0.329261  0.292519  0.315150  0.908502  0.701999
16   0.429746  0.449756  0.864215  0.780469  0.545656
17   0.061255  0.744215  0.492033  0.995704  0.649679
18   0.672779  0.809932  0.884640  0.251496  0.996749
19   0.546001  0.882204  0.065525  0.107970  0.549491
20   0.774763  0.895967  0.442847  0.319242  0.391008
21   0.771038  0.854845  0.248566  0.093187  0.371986
22   0.140288  0.949820  0.598971  0.803375  0.985255
23   0.255859  0.161022  0.775029  0.396540  0.991356
24   0.509633  0.881997  0.920649  0.048840  0.615399
25   0.389427  0.651619  0.464923  0.732137  0.811949
26   0.734640  0.995931  0.759693  0.328819  0.736971
27   0.738787  0.388602  0.775336  0.219706  0.983884
28   0.905255  0.875478  0.088939  0.903236  0.802762
29   0.469015  0.985826  0.696888  0.902970  0.342933
..        ...       ...       ...       ...       ...
300  0.476195  0.121393  0.603848  0.366130  0.834501
301  0.800722  0.662510  0.768460  0.984129  0.154613
302  0.225556  0.865493  0.984356  0.747575  0.646819
303  0.368773  0.658915  0.624956  0.629452  0.354147
304  0.825317  0.779462  0.758485  0.321560  0.913806
305  0.087316  0.812334  0.132241  0.942934  0.803855
306  0.952756  0.808538  0.825270  0.881440  0.267988
307  0.092710  0.693099  0.190337  0.512406  0.078050
308  0.170193  0.932686  0.248047  0.068284  0.612386
309  0.916866  0.786996  0.011374  0.633432  0.071652
310  0.218821  0.449369  0.224524  0.905922  0.781346
311  0.239697  0.684386  0.662704  0.895856  0.633153
312  0.971503  0.252326  0.550695  0.641696  0.888320
313  0.361679  0.038676  0.873438  0.374538  0.990121
314  0.943748  0.643535  0.066310  0.896443  0.799697
315  0.493584  0.625935  0.025109  0.263607  0.469331
316  0.658936  0.306812  0.581688  0.034822  0.730973
317  0.307538  0.298886  0.408116  0.885046  0.422507
318  0.599349  0.233654  0.799768  0.077291  0.290312
319  0.652546  0.492913  0.035755  0.313973  0.175828
320  0.593043  0.516830  0.585891  0.797445  0.721501
321  0.714735  0.914136  0.873655  0.228181  0.818207
322  0.778011  0.809369  0.260071  0.030331  0.179675
323  0.362414  0.973221  0.634051  0.017125  0.992082
324  0.335795  0.226165  0.983408  0.512912  0.651135
325  0.381750  0.113412  0.683215  0.561256  0.760116
326  0.925748  0.690403  0.765359  0.268175  0.518897
327  0.446183  0.865364  0.558433  0.898489  0.719756
328  0.518795  0.715986  0.968898  0.516743  0.289682
329  0.753758  0.590465  0.573078  0.002902  0.902431

[330 rows x 5 columns]

In [22]:
type(df)

pandas.core.frame.DataFrame

In [23]:
df.describe()

                0           1           2           3           4
count  330.000000  330.000000  330.000000  330.000000  330.000000
mean     0.510835    0.518509    0.527363    0.489493    0.523719
std      0.283665    0.288431    0.301396    0.282378    0.295060
min      0.008405    0.001102    0.010188    0.002902    0.002028
25%      0.293337    0.273015    0.253265    0.260898    0.272121
50%      0.520209    0.527768    0.547115    0.475064    0.531728
75%      0.753255    0.774162    0.788439    0.738587    0.799632
max      0.990808    0.997631    0.999300    0.999904    0.998507

In [24]:
df.dtypes

0    float64
1    float64
2    float64
3    float64
4    float64
dtype: object

In [25]:
df.head()

          0         1         2         3         4
0  0.249591  0.400358  0.195161  0.485928  0.784790
1  0.768235  0.774584  0.986698  0.336482  0.408301
2  0.724468  0.604839  0.874132  0.691223  0.439762
3  0.858835  0.380090  0.644773  0.505105  0.329564
4  0.908892  0.772895  0.942653  0.337241  0.461231

In [26]:
df[0][0]='fahad'

In [27]:
df.head()

          0         1         2         3         4
0     fahad  0.400358  0.195161  0.485928  0.784790
1  0.768235  0.774584  0.986698  0.336482  0.408301
2  0.724468  0.604839  0.874132  0.691223  0.439762
3  0.858835  0.380090  0.644773  0.505105  0.329564
4  0.908892  0.772895  0.942653  0.337241  0.461231

In [28]:
df.dtypes

0     object
1    float64
2    float64
3    float64
4    float64
dtype: object

In [29]:
df[3][4]='faisal'

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexing.py:190: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)

In [31]:
df.head()

          0         1         2         3         4
0     fahad  0.400358  0.195161  0.485928  0.784790
1  0.768235  0.774584  0.986698  0.336482  0.408301
2  0.724468  0.604839  0.874132  0.691223  0.439762
3  0.858835  0.380090  0.644773  0.505105  0.329564
4  0.908892  0.772895  0.942653    faisal  0.461231

In [32]:
df.index

RangeIndex(start=0, stop=330, step=1)

<h6>dataframe into numpy</h6>

In [34]:
df.to_numpy()

array([['fahad', 0.40035758718717895, 0.19516148575184267,
        0.48592828017624135, 0.7847901508336528],
       [0.7682348245975624, 0.7745843575213222, 0.9866979394210963,
        0.3364820744826853, 0.40830076460238207],
       [0.7244681840103546, 0.6048392188627333, 0.8741317758363433,
        0.6912228171424073, 0.4397624075364347],
       ...,
       [0.4461829148847173, 0.8653641911414313, 0.5584332016338335,
        0.8984892284113823, 0.7197555421285806],
       [0.5187950948203657, 0.7159863433508151, 0.968898097940501,
        0.5167433684840428, 0.2896824649890678],
       [0.7537575854590207, 0.590465129966354, 0.5730779469980346,
        0.002902276397057424, 0.9024308998935446]], dtype=object)

In [36]:
df.T

,0,1,2,3,4,5,6,7,8,9,...,320,321,322,323,324,325,326,327,328,329
0,fahad,0.768235,0.724468,0.858835,0.908892,0.186932,0.42097,0.127323,0.737604,0.943722,...,0.593043,0.714735,0.778011,0.362414,0.335795,0.38175,0.925748,0.446183,0.518795,0.753758
1,0.400358,0.774584,0.604839,0.38009,0.772895,0.972758,0.809826,0.374748,0.171895,0.781767,...,0.51683,0.914136,0.809369,0.973221,0.226165,0.113412,0.690403,0.865364,0.715986,0.590465
2,0.195161,0.986698,0.874132,0.644773,0.942653,0.446872,0.549558,0.138717,0.93298,0.75692,...,0.585891,0.873655,0.260071,0.634051,0.983408,0.683215,0.765359,0.558433,0.968898,0.573078
3,0.485928,0.336482,0.691223,0.505105,faisal,0.644623,0.116722,0.883066,0.0904653,0.245574,...,0.797445,0.228181,0.0303313,0.0171246,0.512912,0.561256,0.268175,0.898489,0.516743,0.00290228
4,0.78479,0.408301,0.439762,0.329564,0.461231,0.370857,0.277077,0.298136,0.196444,0.553133,...,0.721501,0.818207,0.179675,0.992082,0.651135,0.760116,0.518897,0.719756,0.289682,0.902431

In [43]:
df.sort_index(axis=0,ascending=False)

             0         1         2           3         4
329   0.753758  0.590465  0.573078  0.00290228  0.902431
328   0.518795  0.715986  0.968898    0.516743  0.289682
327   0.446183  0.865364  0.558433    0.898489  0.719756
326   0.925748  0.690403  0.765359    0.268175  0.518897
325    0.38175  0.113412  0.683215    0.561256  0.760116
324   0.335795  0.226165  0.983408    0.512912  0.651135
323   0.362414  0.973221  0.634051   0.0171246  0.992082
322   0.778011  0.809369  0.260071   0.0303313  0.179675
321   0.714735  0.914136  0.873655    0.228181  0.818207
320   0.593043  0.516830  0.585891    0.797445  0.721501
319   0.652546  0.492913  0.035755    0.313973  0.175828
318   0.599349  0.233654  0.799768   0.0772909  0.290312
317   0.307538  0.298886  0.408116    0.885046  0.422507
316   0.658936  0.306812  0.581688   0.0348218  0.730973
315   0.493584  0.625935  0.025109    0.263607  0.469331
314   0.943748  0.643535  0.066310    0.896443  0.799697
313   0.361679  0.038676  0.873438    0.374538  0.990121
312   0.971503  0.252326  0.550695    0.641696  0.888320
311   0.239697  0.684386  0.662704    0.895856  0.633153
310   0.218821  0.449369  0.224524    0.905922  0.781346
309   0.916866  0.786996  0.011374    0.633432  0.071652
308   0.170193  0.932686  0.248047   0.0682845  0.612386
307  0.0927098  0.693099  0.190337    0.512406  0.078050
306   0.952756  0.808538  0.825270     0.88144  0.267988
305  0.0873156  0.812334  0.132241    0.942934  0.803855
304   0.825317  0.779462  0.758485     0.32156  0.913806
303   0.368773  0.658915  0.624956    0.629452  0.354147
302   0.225556  0.865493  0.984356    0.747575  0.646819
301   0.800722  0.662510  0.768460    0.984129  0.154613
300   0.476195  0.121393  0.603848     0.36613  0.834501
..         ...       ...       ...         ...       ...
29    0.469015  0.985826  0.696888     0.90297  0.342933
28    0.905255  0.875478  0.088939    0.903236  0.802762
27    0.738787  0.388602  0.775336    0.219706  0.983884
26     0.73464  0.995931  0.759693    0.328819  0.736971
25    0.389427  0.651619  0.464923    0.732137  0.811949
24    0.509633  0.881997  0.920649   0.0488397  0.615399
23    0.255859  0.161022  0.775029     0.39654  0.991356
22    0.140288  0.949820  0.598971    0.803375  0.985255
21    0.771038  0.854845  0.248566   0.0931869  0.371986
20    0.774763  0.895967  0.442847    0.319242  0.391008
19    0.546001  0.882204  0.065525     0.10797  0.549491
18    0.672779  0.809932  0.884640    0.251496  0.996749
17   0.0612547  0.744215  0.492033    0.995704  0.649679
16    0.429746  0.449756  0.864215    0.780469  0.545656
15    0.329261  0.292519  0.315150    0.908502  0.701999
14   0.0944537  0.481045  0.469216    0.655201  0.336626
13    0.900518  0.240991  0.984663    0.101751  0.332327
12    0.792973  0.863136  0.237447    0.858588  0.685894
11    0.408782  0.483285  0.218606    0.986162  0.626893
10    0.224846  0.004142  0.024532    0.971419  0.795797
9     0.943722  0.781767  0.756920    0.245574  0.553133
8     0.737604  0.171895  0.932980   0.0904653  0.196444
7     0.127323  0.374748  0.138717    0.883066  0.298136
6      0.42097  0.809826  0.549558    0.116722  0.277077
5     0.186932  0.972758  0.446872    0.644623  0.370857
4     0.908892  0.772895  0.942653      faisal  0.461231
3     0.858835  0.380090  0.644773    0.505105  0.329564
2     0.724468  0.604839  0.874132    0.691223  0.439762
1     0.768235  0.774584  0.986698    0.336482  0.408301
0        fahad  0.400358  0.195161    0.485928  0.784790

[330 rows x 5 columns]

<h6> View data </h6>

In [44]:
newdf=df

In [51]:
newdf[0][0]=0.5

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [57]:
df

             0         1         2           3         4  (0, 0)
0          0.5  0.400358  0.195161    0.485928  0.784790     0.5
1     0.768235  0.774584  0.986698    0.336482  0.408301     0.5
2     0.724468  0.604839  0.874132    0.691223  0.439762     0.5
3     0.858835  0.380090  0.644773    0.505105  0.329564     0.5
4     0.908892  0.772895  0.942653      faisal  0.461231     0.5
5     0.186932  0.972758  0.446872    0.644623  0.370857     0.5
6      0.42097  0.809826  0.549558    0.116722  0.277077     0.5
7     0.127323  0.374748  0.138717    0.883066  0.298136     0.5
8     0.737604  0.171895  0.932980   0.0904653  0.196444     0.5
9     0.943722  0.781767  0.756920    0.245574  0.553133     0.5
10    0.224846  0.004142  0.024532    0.971419  0.795797     0.5
11    0.408782  0.483285  0.218606    0.986162  0.626893     0.5
12    0.792973  0.863136  0.237447    0.858588  0.685894     0.5
13    0.900518  0.240991  0.984663    0.101751  0.332327     0.5
14   0.0944537  0.481045  0.469216    0.655201  0.336626     0.5
15    0.329261  0.292519  0.315150    0.908502  0.701999     0.5
16    0.429746  0.449756  0.864215    0.780469  0.545656     0.5
17   0.0612547  0.744215  0.492033    0.995704  0.649679     0.5
18    0.672779  0.809932  0.884640    0.251496  0.996749     0.5
19    0.546001  0.882204  0.065525     0.10797  0.549491     0.5
20    0.774763  0.895967  0.442847    0.319242  0.391008     0.5
21    0.771038  0.854845  0.248566   0.0931869  0.371986     0.5
22    0.140288  0.949820  0.598971    0.803375  0.985255     0.5
23    0.255859  0.161022  0.775029     0.39654  0.991356     0.5
24    0.509633  0.881997  0.920649   0.0488397  0.615399     0.5
25    0.389427  0.651619  0.464923    0.732137  0.811949     0.5
26     0.73464  0.995931  0.759693    0.328819  0.736971     0.5
27    0.738787  0.388602  0.775336    0.219706  0.983884     0.5
28    0.905255  0.875478  0.088939    0.903236  0.802762     0.5
29    0.469015  0.985826  0.696888     0.90297  0.342933     0.5
..         ...       ...       ...         ...       ...     ...
300   0.476195  0.121393  0.603848     0.36613  0.834501     0.5
301   0.800722  0.662510  0.768460    0.984129  0.154613     0.5
302   0.225556  0.865493  0.984356    0.747575  0.646819     0.5
303   0.368773  0.658915  0.624956    0.629452  0.354147     0.5
304   0.825317  0.779462  0.758485     0.32156  0.913806     0.5
305  0.0873156  0.812334  0.132241    0.942934  0.803855     0.5
306   0.952756  0.808538  0.825270     0.88144  0.267988     0.5
307  0.0927098  0.693099  0.190337    0.512406  0.078050     0.5
308   0.170193  0.932686  0.248047   0.0682845  0.612386     0.5
309   0.916866  0.786996  0.011374    0.633432  0.071652     0.5
310   0.218821  0.449369  0.224524    0.905922  0.781346     0.5
311   0.239697  0.684386  0.662704    0.895856  0.633153     0.5
312   0.971503  0.252326  0.550695    0.641696  0.888320     0.5
313   0.361679  0.038676  0.873438    0.374538  0.990121     0.5
314   0.943748  0.643535  0.066310    0.896443  0.799697     0.5
315   0.493584  0.625935  0.025109    0.263607  0.469331     0.5
316   0.658936  0.306812  0.581688   0.0348218  0.730973     0.5
317   0.307538  0.298886  0.408116    0.885046  0.422507     0.5
318   0.599349  0.233654  0.799768   0.0772909  0.290312     0.5
319   0.652546  0.492913  0.035755    0.313973  0.175828     0.5
320   0.593043  0.516830  0.585891    0.797445  0.721501     0.5
321   0.714735  0.914136  0.873655    0.228181  0.818207     0.5
322   0.778011  0.809369  0.260071   0.0303313  0.179675     0.5
323   0.362414  0.973221  0.634051   0.0171246  0.992082     0.5
324   0.335795  0.226165  0.983408    0.512912  0.651135     0.5
325    0.38175  0.113412  0.683215    0.561256  0.760116     0.5
326   0.925748  0.690403  0.765359    0.268175  0.518897     0.5
327   0.446183  0.865364  0.558433    0.898489  0.719756     0.5
328   0.518795  0.715986  0.968898    0.516743  0.289682     0.5
329   0.753758  0.590465  0.573078  0.00290228  0.902431     0.5

[330 rows x 6 columns]

<h6> deleting the column</h6>

In [58]:
df.drop((0,0),axis=1)

             0         1         2           3         4
0          0.5  0.400358  0.195161    0.485928  0.784790
1     0.768235  0.774584  0.986698    0.336482  0.408301
2     0.724468  0.604839  0.874132    0.691223  0.439762
3     0.858835  0.380090  0.644773    0.505105  0.329564
4     0.908892  0.772895  0.942653      faisal  0.461231
5     0.186932  0.972758  0.446872    0.644623  0.370857
6      0.42097  0.809826  0.549558    0.116722  0.277077
7     0.127323  0.374748  0.138717    0.883066  0.298136
8     0.737604  0.171895  0.932980   0.0904653  0.196444
9     0.943722  0.781767  0.756920    0.245574  0.553133
10    0.224846  0.004142  0.024532    0.971419  0.795797
11    0.408782  0.483285  0.218606    0.986162  0.626893
12    0.792973  0.863136  0.237447    0.858588  0.685894
13    0.900518  0.240991  0.984663    0.101751  0.332327
14   0.0944537  0.481045  0.469216    0.655201  0.336626
15    0.329261  0.292519  0.315150    0.908502  0.701999
16    0.429746  0.449756  0.864215    0.780469  0.545656
17   0.0612547  0.744215  0.492033    0.995704  0.649679
18    0.672779  0.809932  0.884640    0.251496  0.996749
19    0.546001  0.882204  0.065525     0.10797  0.549491
20    0.774763  0.895967  0.442847    0.319242  0.391008
21    0.771038  0.854845  0.248566   0.0931869  0.371986
22    0.140288  0.949820  0.598971    0.803375  0.985255
23    0.255859  0.161022  0.775029     0.39654  0.991356
24    0.509633  0.881997  0.920649   0.0488397  0.615399
25    0.389427  0.651619  0.464923    0.732137  0.811949
26     0.73464  0.995931  0.759693    0.328819  0.736971
27    0.738787  0.388602  0.775336    0.219706  0.983884
28    0.905255  0.875478  0.088939    0.903236  0.802762
29    0.469015  0.985826  0.696888     0.90297  0.342933
..         ...       ...       ...         ...       ...
300   0.476195  0.121393  0.603848     0.36613  0.834501
301   0.800722  0.662510  0.768460    0.984129  0.154613
302   0.225556  0.865493  0.984356    0.747575  0.646819
303   0.368773  0.658915  0.624956    0.629452  0.354147
304   0.825317  0.779462  0.758485     0.32156  0.913806
305  0.0873156  0.812334  0.132241    0.942934  0.803855
306   0.952756  0.808538  0.825270     0.88144  0.267988
307  0.0927098  0.693099  0.190337    0.512406  0.078050
308   0.170193  0.932686  0.248047   0.0682845  0.612386
309   0.916866  0.786996  0.011374    0.633432  0.071652
310   0.218821  0.449369  0.224524    0.905922  0.781346
311   0.239697  0.684386  0.662704    0.895856  0.633153
312   0.971503  0.252326  0.550695    0.641696  0.888320
313   0.361679  0.038676  0.873438    0.374538  0.990121
314   0.943748  0.643535  0.066310    0.896443  0.799697
315   0.493584  0.625935  0.025109    0.263607  0.469331
316   0.658936  0.306812  0.581688   0.0348218  0.730973
317   0.307538  0.298886  0.408116    0.885046  0.422507
318   0.599349  0.233654  0.799768   0.0772909  0.290312
319   0.652546  0.492913  0.035755    0.313973  0.175828
320   0.593043  0.516830  0.585891    0.797445  0.721501
321   0.714735  0.914136  0.873655    0.228181  0.818207
322   0.778011  0.809369  0.260071   0.0303313  0.179675
323   0.362414  0.973221  0.634051   0.0171246  0.992082
324   0.335795  0.226165  0.983408    0.512912  0.651135
325    0.38175  0.113412  0.683215    0.561256  0.760116
326   0.925748  0.690403  0.765359    0.268175  0.518897
327   0.446183  0.865364  0.558433    0.898489  0.719756
328   0.518795  0.715986  0.968898    0.516743  0.289682
329   0.753758  0.590465  0.573078  0.00290228  0.902431

[330 rows x 5 columns]

<h6>Copying the data  and changing the values</h6>

In [56]:
newdf=df.copy()

In [61]:
newdf.drop((0,0),axis=1)

             0         1         2           3         4
0          0.5  0.400358  0.195161    0.485928  0.784790
1     0.768235  0.774584  0.986698    0.336482  0.408301
2     0.724468  0.604839  0.874132    0.691223  0.439762
3     0.858835  0.380090  0.644773    0.505105  0.329564
4     0.908892  0.772895  0.942653      faisal  0.461231
5     0.186932  0.972758  0.446872    0.644623  0.370857
6      0.42097  0.809826  0.549558    0.116722  0.277077
7     0.127323  0.374748  0.138717    0.883066  0.298136
8     0.737604  0.171895  0.932980   0.0904653  0.196444
9     0.943722  0.781767  0.756920    0.245574  0.553133
10    0.224846  0.004142  0.024532    0.971419  0.795797
11    0.408782  0.483285  0.218606    0.986162  0.626893
12    0.792973  0.863136  0.237447    0.858588  0.685894
13    0.900518  0.240991  0.984663    0.101751  0.332327
14   0.0944537  0.481045  0.469216    0.655201  0.336626
15    0.329261  0.292519  0.315150    0.908502  0.701999
16    0.429746  0.449756  0.864215    0.780469  0.545656
17   0.0612547  0.744215  0.492033    0.995704  0.649679
18    0.672779  0.809932  0.884640    0.251496  0.996749
19    0.546001  0.882204  0.065525     0.10797  0.549491
20    0.774763  0.895967  0.442847    0.319242  0.391008
21    0.771038  0.854845  0.248566   0.0931869  0.371986
22    0.140288  0.949820  0.598971    0.803375  0.985255
23    0.255859  0.161022  0.775029     0.39654  0.991356
24    0.509633  0.881997  0.920649   0.0488397  0.615399
25    0.389427  0.651619  0.464923    0.732137  0.811949
26     0.73464  0.995931  0.759693    0.328819  0.736971
27    0.738787  0.388602  0.775336    0.219706  0.983884
28    0.905255  0.875478  0.088939    0.903236  0.802762
29    0.469015  0.985826  0.696888     0.90297  0.342933
..         ...       ...       ...         ...       ...
300   0.476195  0.121393  0.603848     0.36613  0.834501
301   0.800722  0.662510  0.768460    0.984129  0.154613
302   0.225556  0.865493  0.984356    0.747575  0.646819
303   0.368773  0.658915  0.624956    0.629452  0.354147
304   0.825317  0.779462  0.758485     0.32156  0.913806
305  0.0873156  0.812334  0.132241    0.942934  0.803855
306   0.952756  0.808538  0.825270     0.88144  0.267988
307  0.0927098  0.693099  0.190337    0.512406  0.078050
308   0.170193  0.932686  0.248047   0.0682845  0.612386
309   0.916866  0.786996  0.011374    0.633432  0.071652
310   0.218821  0.449369  0.224524    0.905922  0.781346
311   0.239697  0.684386  0.662704    0.895856  0.633153
312   0.971503  0.252326  0.550695    0.641696  0.888320
313   0.361679  0.038676  0.873438    0.374538  0.990121
314   0.943748  0.643535  0.066310    0.896443  0.799697
315   0.493584  0.625935  0.025109    0.263607  0.469331
316   0.658936  0.306812  0.581688   0.0348218  0.730973
317   0.307538  0.298886  0.408116    0.885046  0.422507
318   0.599349  0.233654  0.799768   0.0772909  0.290312
319   0.652546  0.492913  0.035755    0.313973  0.175828
320   0.593043  0.516830  0.585891    0.797445  0.721501
321   0.714735  0.914136  0.873655    0.228181  0.818207
322   0.778011  0.809369  0.260071   0.0303313  0.179675
323   0.362414  0.973221  0.634051   0.0171246  0.992082
324   0.335795  0.226165  0.983408    0.512912  0.651135
325    0.38175  0.113412  0.683215    0.561256  0.760116
326   0.925748  0.690403  0.765359    0.268175  0.518897
327   0.446183  0.865364  0.558433    0.898489  0.719756
328   0.518795  0.715986  0.968898    0.516743  0.289682
329   0.753758  0.590465  0.573078  0.00290228  0.902431

[330 rows x 5 columns]

In [62]:
newdf[0][0] = 0.2411

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [67]:
newdf.drop((0,0),axis=1)

             0         1         2           3         4
0       0.2411  0.400358  0.195161    0.485928  0.784790
1     0.768235  0.774584  0.986698    0.336482  0.408301
2     0.724468  0.604839  0.874132    0.691223  0.439762
3     0.858835  0.380090  0.644773    0.505105  0.329564
4     0.908892  0.772895  0.942653      faisal  0.461231
5     0.186932  0.972758  0.446872    0.644623  0.370857
6      0.42097  0.809826  0.549558    0.116722  0.277077
7     0.127323  0.374748  0.138717    0.883066  0.298136
8     0.737604  0.171895  0.932980   0.0904653  0.196444
9     0.943722  0.781767  0.756920    0.245574  0.553133
10    0.224846  0.004142  0.024532    0.971419  0.795797
11    0.408782  0.483285  0.218606    0.986162  0.626893
12    0.792973  0.863136  0.237447    0.858588  0.685894
13    0.900518  0.240991  0.984663    0.101751  0.332327
14   0.0944537  0.481045  0.469216    0.655201  0.336626
15    0.329261  0.292519  0.315150    0.908502  0.701999
16    0.429746  0.449756  0.864215    0.780469  0.545656
17   0.0612547  0.744215  0.492033    0.995704  0.649679
18    0.672779  0.809932  0.884640    0.251496  0.996749
19    0.546001  0.882204  0.065525     0.10797  0.549491
20    0.774763  0.895967  0.442847    0.319242  0.391008
21    0.771038  0.854845  0.248566   0.0931869  0.371986
22    0.140288  0.949820  0.598971    0.803375  0.985255
23    0.255859  0.161022  0.775029     0.39654  0.991356
24    0.509633  0.881997  0.920649   0.0488397  0.615399
25    0.389427  0.651619  0.464923    0.732137  0.811949
26     0.73464  0.995931  0.759693    0.328819  0.736971
27    0.738787  0.388602  0.775336    0.219706  0.983884
28    0.905255  0.875478  0.088939    0.903236  0.802762
29    0.469015  0.985826  0.696888     0.90297  0.342933
..         ...       ...       ...         ...       ...
300   0.476195  0.121393  0.603848     0.36613  0.834501
301   0.800722  0.662510  0.768460    0.984129  0.154613
302   0.225556  0.865493  0.984356    0.747575  0.646819
303   0.368773  0.658915  0.624956    0.629452  0.354147
304   0.825317  0.779462  0.758485     0.32156  0.913806
305  0.0873156  0.812334  0.132241    0.942934  0.803855
306   0.952756  0.808538  0.825270     0.88144  0.267988
307  0.0927098  0.693099  0.190337    0.512406  0.078050
308   0.170193  0.932686  0.248047   0.0682845  0.612386
309   0.916866  0.786996  0.011374    0.633432  0.071652
310   0.218821  0.449369  0.224524    0.905922  0.781346
311   0.239697  0.684386  0.662704    0.895856  0.633153
312   0.971503  0.252326  0.550695    0.641696  0.888320
313   0.361679  0.038676  0.873438    0.374538  0.990121
314   0.943748  0.643535  0.066310    0.896443  0.799697
315   0.493584  0.625935  0.025109    0.263607  0.469331
316   0.658936  0.306812  0.581688   0.0348218  0.730973
317   0.307538  0.298886  0.408116    0.885046  0.422507
318   0.599349  0.233654  0.799768   0.0772909  0.290312
319   0.652546  0.492913  0.035755    0.313973  0.175828
320   0.593043  0.516830  0.585891    0.797445  0.721501
321   0.714735  0.914136  0.873655    0.228181  0.818207
322   0.778011  0.809369  0.260071   0.0303313  0.179675
323   0.362414  0.973221  0.634051   0.0171246  0.992082
324   0.335795  0.226165  0.983408    0.512912  0.651135
325    0.38175  0.113412  0.683215    0.561256  0.760116
326   0.925748  0.690403  0.765359    0.268175  0.518897
327   0.446183  0.865364  0.558433    0.898489  0.719756
328   0.518795  0.715986  0.968898    0.516743  0.289682
329   0.753758  0.590465  0.573078  0.00290228  0.902431

[330 rows x 5 columns]

In [69]:
newdf=newdf.drop((0,0),axis=1)

In [70]:
newdf.head()

          0         1         2         3         4
0    0.2411  0.400358  0.195161  0.485928  0.784790
1  0.768235  0.774584  0.986698  0.336482  0.408301
2  0.724468  0.604839  0.874132  0.691223  0.439762
3  0.858835  0.380090  0.644773  0.505105  0.329564
4  0.908892  0.772895  0.942653    faisal  0.461231

<h6> setting the row and column</h6>

In [72]:
newdf.loc[[0,1,2],[0,2,3]]

          0         2         3
0    0.2411  0.195161  0.485928
1  0.768235  0.986698  0.336482
2  0.724468  0.874132  0.691223

In [74]:
newdf.loc[[0,2],:]

          0         1         2         3         4
0    0.2411  0.400358  0.195161  0.485928  0.784790
2  0.724468  0.604839  0.874132  0.691223  0.439762

In [79]:
newdf.loc[(newdf(0)<0.25)]

TypeError: 'DataFrame' object is not callable

In [80]:
newdf.iloc[0,4]

0.7847901508336528

In [81]:
newdf.iloc[[0,3],[0,2]]

          0         2
0    0.2411  0.195161
3  0.858835  0.644773

In [82]:
newdf.head()

          0         1         2         3         4
0    0.2411  0.400358  0.195161  0.485928  0.784790
1  0.768235  0.774584  0.986698  0.336482  0.408301
2  0.724468  0.604839  0.874132  0.691223  0.439762
3  0.858835  0.380090  0.644773  0.505105  0.329564
4  0.908892  0.772895  0.942653    faisal  0.461231

In [83]:
newdf.drop(0,axis=0)

             0         1         2           3         4
1     0.768235  0.774584  0.986698    0.336482  0.408301
2     0.724468  0.604839  0.874132    0.691223  0.439762
3     0.858835  0.380090  0.644773    0.505105  0.329564
4     0.908892  0.772895  0.942653      faisal  0.461231
5     0.186932  0.972758  0.446872    0.644623  0.370857
6      0.42097  0.809826  0.549558    0.116722  0.277077
7     0.127323  0.374748  0.138717    0.883066  0.298136
8     0.737604  0.171895  0.932980   0.0904653  0.196444
9     0.943722  0.781767  0.756920    0.245574  0.553133
10    0.224846  0.004142  0.024532    0.971419  0.795797
11    0.408782  0.483285  0.218606    0.986162  0.626893
12    0.792973  0.863136  0.237447    0.858588  0.685894
13    0.900518  0.240991  0.984663    0.101751  0.332327
14   0.0944537  0.481045  0.469216    0.655201  0.336626
15    0.329261  0.292519  0.315150    0.908502  0.701999
16    0.429746  0.449756  0.864215    0.780469  0.545656
17   0.0612547  0.744215  0.492033    0.995704  0.649679
18    0.672779  0.809932  0.884640    0.251496  0.996749
19    0.546001  0.882204  0.065525     0.10797  0.549491
20    0.774763  0.895967  0.442847    0.319242  0.391008
21    0.771038  0.854845  0.248566   0.0931869  0.371986
22    0.140288  0.949820  0.598971    0.803375  0.985255
23    0.255859  0.161022  0.775029     0.39654  0.991356
24    0.509633  0.881997  0.920649   0.0488397  0.615399
25    0.389427  0.651619  0.464923    0.732137  0.811949
26     0.73464  0.995931  0.759693    0.328819  0.736971
27    0.738787  0.388602  0.775336    0.219706  0.983884
28    0.905255  0.875478  0.088939    0.903236  0.802762
29    0.469015  0.985826  0.696888     0.90297  0.342933
30    0.700376  0.258960  0.767684    0.853074  0.991282
..         ...       ...       ...         ...       ...
300   0.476195  0.121393  0.603848     0.36613  0.834501
301   0.800722  0.662510  0.768460    0.984129  0.154613
302   0.225556  0.865493  0.984356    0.747575  0.646819
303   0.368773  0.658915  0.624956    0.629452  0.354147
304   0.825317  0.779462  0.758485     0.32156  0.913806
305  0.0873156  0.812334  0.132241    0.942934  0.803855
306   0.952756  0.808538  0.825270     0.88144  0.267988
307  0.0927098  0.693099  0.190337    0.512406  0.078050
308   0.170193  0.932686  0.248047   0.0682845  0.612386
309   0.916866  0.786996  0.011374    0.633432  0.071652
310   0.218821  0.449369  0.224524    0.905922  0.781346
311   0.239697  0.684386  0.662704    0.895856  0.633153
312   0.971503  0.252326  0.550695    0.641696  0.888320
313   0.361679  0.038676  0.873438    0.374538  0.990121
314   0.943748  0.643535  0.066310    0.896443  0.799697
315   0.493584  0.625935  0.025109    0.263607  0.469331
316   0.658936  0.306812  0.581688   0.0348218  0.730973
317   0.307538  0.298886  0.408116    0.885046  0.422507
318   0.599349  0.233654  0.799768   0.0772909  0.290312
319   0.652546  0.492913  0.035755    0.313973  0.175828
320   0.593043  0.516830  0.585891    0.797445  0.721501
321   0.714735  0.914136  0.873655    0.228181  0.818207
322   0.778011  0.809369  0.260071   0.0303313  0.179675
323   0.362414  0.973221  0.634051   0.0171246  0.992082
324   0.335795  0.226165  0.983408    0.512912  0.651135
325    0.38175  0.113412  0.683215    0.561256  0.760116
326   0.925748  0.690403  0.765359    0.268175  0.518897
327   0.446183  0.865364  0.558433    0.898489  0.719756
328   0.518795  0.715986  0.968898    0.516743  0.289682
329   0.753758  0.590465  0.573078  0.00290228  0.902431

[329 rows x 5 columns]

<h6>reset for the index</h6>

In [84]:
newdf.reset_index(drop=True)

             0         1         2           3         4
0       0.2411  0.400358  0.195161    0.485928  0.784790
1     0.768235  0.774584  0.986698    0.336482  0.408301
2     0.724468  0.604839  0.874132    0.691223  0.439762
3     0.858835  0.380090  0.644773    0.505105  0.329564
4     0.908892  0.772895  0.942653      faisal  0.461231
5     0.186932  0.972758  0.446872    0.644623  0.370857
6      0.42097  0.809826  0.549558    0.116722  0.277077
7     0.127323  0.374748  0.138717    0.883066  0.298136
8     0.737604  0.171895  0.932980   0.0904653  0.196444
9     0.943722  0.781767  0.756920    0.245574  0.553133
10    0.224846  0.004142  0.024532    0.971419  0.795797
11    0.408782  0.483285  0.218606    0.986162  0.626893
12    0.792973  0.863136  0.237447    0.858588  0.685894
13    0.900518  0.240991  0.984663    0.101751  0.332327
14   0.0944537  0.481045  0.469216    0.655201  0.336626
15    0.329261  0.292519  0.315150    0.908502  0.701999
16    0.429746  0.449756  0.864215    0.780469  0.545656
17   0.0612547  0.744215  0.492033    0.995704  0.649679
18    0.672779  0.809932  0.884640    0.251496  0.996749
19    0.546001  0.882204  0.065525     0.10797  0.549491
20    0.774763  0.895967  0.442847    0.319242  0.391008
21    0.771038  0.854845  0.248566   0.0931869  0.371986
22    0.140288  0.949820  0.598971    0.803375  0.985255
23    0.255859  0.161022  0.775029     0.39654  0.991356
24    0.509633  0.881997  0.920649   0.0488397  0.615399
25    0.389427  0.651619  0.464923    0.732137  0.811949
26     0.73464  0.995931  0.759693    0.328819  0.736971
27    0.738787  0.388602  0.775336    0.219706  0.983884
28    0.905255  0.875478  0.088939    0.903236  0.802762
29    0.469015  0.985826  0.696888     0.90297  0.342933
..         ...       ...       ...         ...       ...
300   0.476195  0.121393  0.603848     0.36613  0.834501
301   0.800722  0.662510  0.768460    0.984129  0.154613
302   0.225556  0.865493  0.984356    0.747575  0.646819
303   0.368773  0.658915  0.624956    0.629452  0.354147
304   0.825317  0.779462  0.758485     0.32156  0.913806
305  0.0873156  0.812334  0.132241    0.942934  0.803855
306   0.952756  0.808538  0.825270     0.88144  0.267988
307  0.0927098  0.693099  0.190337    0.512406  0.078050
308   0.170193  0.932686  0.248047   0.0682845  0.612386
309   0.916866  0.786996  0.011374    0.633432  0.071652
310   0.218821  0.449369  0.224524    0.905922  0.781346
311   0.239697  0.684386  0.662704    0.895856  0.633153
312   0.971503  0.252326  0.550695    0.641696  0.888320
313   0.361679  0.038676  0.873438    0.374538  0.990121
314   0.943748  0.643535  0.066310    0.896443  0.799697
315   0.493584  0.625935  0.025109    0.263607  0.469331
316   0.658936  0.306812  0.581688   0.0348218  0.730973
317   0.307538  0.298886  0.408116    0.885046  0.422507
318   0.599349  0.233654  0.799768   0.0772909  0.290312
319   0.652546  0.492913  0.035755    0.313973  0.175828
320   0.593043  0.516830  0.585891    0.797445  0.721501
321   0.714735  0.914136  0.873655    0.228181  0.818207
322   0.778011  0.809369  0.260071   0.0303313  0.179675
323   0.362414  0.973221  0.634051   0.0171246  0.992082
324   0.335795  0.226165  0.983408    0.512912  0.651135
325    0.38175  0.113412  0.683215    0.561256  0.760116
326   0.925748  0.690403  0.765359    0.268175  0.518897
327   0.446183  0.865364  0.558433    0.898489  0.719756
328   0.518795  0.715986  0.968898    0.516743  0.289682
329   0.753758  0.590465  0.573078  0.00290228  0.902431

[330 rows x 5 columns]

<h6>Searching for null values</h6>

In [86]:
newdf.isnull()

         0      1      2      3      4
0    False  False  False  False  False
1    False  False  False  False  False
2    False  False  False  False  False
3    False  False  False  False  False
4    False  False  False  False  False
5    False  False  False  False  False
6    False  False  False  False  False
7    False  False  False  False  False
8    False  False  False  False  False
9    False  False  False  False  False
10   False  False  False  False  False
11   False  False  False  False  False
12   False  False  False  False  False
13   False  False  False  False  False
14   False  False  False  False  False
15   False  False  False  False  False
16   False  False  False  False  False
17   False  False  False  False  False
18   False  False  False  False  False
19   False  False  False  False  False
20   False  False  False  False  False
21   False  False  False  False  False
22   False  False  False  False  False
23   False  False  False  False  False
24   False  False  False  False  False
25   False  False  False  False  False
26   False  False  False  False  False
27   False  False  False  False  False
28   False  False  False  False  False
29   False  False  False  False  False
..     ...    ...    ...    ...    ...
300  False  False  False  False  False
301  False  False  False  False  False
302  False  False  False  False  False
303  False  False  False  False  False
304  False  False  False  False  False
305  False  False  False  False  False
306  False  False  False  False  False
307  False  False  False  False  False
308  False  False  False  False  False
309  False  False  False  False  False
310  False  False  False  False  False
311  False  False  False  False  False
312  False  False  False  False  False
313  False  False  False  False  False
314  False  False  False  False  False
315  False  False  False  False  False
316  False  False  False  False  False
317  False  False  False  False  False
318  False  False  False  False  False
319  False  False  False  False  False
320  False  False  False  False  False
321  False  False  False  False  False
322  False  False  False  False  False
323  False  False  False  False  False
324  False  False  False  False  False
325  False  False  False  False  False
326  False  False  False  False  False
327  False  False  False  False  False
328  False  False  False  False  False
329  False  False  False  False  False

[330 rows x 5 columns]